FROM golang:1.18-alpine

ENV DATA_PATH=/data

ENV HOSTNAME=

ENV PORT=80

EXPOSE 80

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

CMD app --host=${HOSTNAME} --port=${port} --path=${PATH_DATA}
